### ISSUE TITLE
cannot run task 2

### ISSUE THREAD

**Issue by SoyMark** [LogCreative/mnist-calculator#1]
你好！很感谢的你的分享，task3我可以顺利运行，但是task2我这里会报错： '< Infer >d__6' object has no attribute 'GetEnumerator'。我仔细看了一下代码，逻辑应该是没有问题的，错误发生在inferResult = self.model.Infer(imageWrapper);这一行之后，inferresult的类型是 '< Infer >d__6'，而非应有的IEnumerator<IEnumerator<T>>。因此会报出：没有这个GetEnumertator的错误。不知道你是否有遇到呢？

**Comment by LogCreative** [comment]
我在另一台电脑上复现了这个问题，原因是你可能安装`pythonnet`时，使用了
```cmd
pip install pythonnet
```
这会安装稳定版本（2.5.2），但是这个项目采用的
```cmd
cd pythonnet
pip install .
```
使用的是开发版本（3.0.0a1），API调用产生了一定的不同，就会导致这个错误，以及其他的任何调用dll操作都会导致错误。

如果不想从源码编译pythonnet，可以尝试使用
```cmd
pip install pythonnet==3.0.0a1
```

**Comment by SoyMark** [comment]
非常感谢！
